apiVersion: v1
kind: Service
metadata:
  name: am-service
  namespace: accountmanagement
  labels:
    run: am-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: accountmanagement